"""产物三件套：C 数组、bin、manifest。确定性生成：REGISTRY 顺序、固定换行、ASCII。
生成文件只用 <stdint.h> 类型（core 宿主可编译前提；EDK2 VS2019 兼容）。"""
import json, zlib
from pathlib import Path
from tables import entry_bytes

def c_ident(name):
    s = ''.join(ch if (ch.isalnum() or ch == '_') else '_' for ch in name)
    return ('_' + s) if s[:1].isdigit() else s

def _hex_lines(data, per_line=12):
    return ['    ' + ','.join(f'0x{b:02X}' for b in data[i:i+per_line]) + ','
            for i in range(0, len(data), per_line)]

def _emit_prg_banks(rom, gen, bindir, manifest):
    """全 PRG 镜像：bank 切换语义（BankRead8/BankPtr）的运行数据源。"""
    c_parts = ['/* Auto-generated by tools/rom_extract. DO NOT EDIT. */',
               '#include "jackal_prg_banks.h"', '']
    h_parts = ['/* Auto-generated by tools/rom_extract. DO NOT EDIT. */',
               '#ifndef JACKAL_PRG_BANKS_H', '#define JACKAL_PRG_BANKS_H', '',
               '#include <stdint.h>', '',
               '#define JACKAL_PRG_BANK_COUNT 8',
               '#define JACKAL_PRG_BANK_SIZE  0x4000', '',
               'extern const uint8_t JackalPrgBanks[JACKAL_PRG_BANK_COUNT][JACKAL_PRG_BANK_SIZE];',
               '', '#endif']
    rows = []
    for n in range(8):
        data = bytes(rom.banks[n])
        (bindir / f'prg_bank_{n}.bin').write_bytes(data)
        rows.append('  {')
        rows += ['  ' + ln for ln in _hex_lines(data, 16)]
        rows.append('  },')
        manifest['entries'].append({
            'name': f'prg_bank_{n}', 'bank': n,
            'cpu': '0xC000' if n == 7 else '0x8000',
            'kind': 'prg_bank', 'count': 0x4000, 'length': 0x4000,
            'crc32': f'0x{zlib.crc32(data) & 0xFFFFFFFF:08X}',
            'asm_ref': 'MAIN.asm (iNES PRG layout)',
            'evidence': 'rom.banks slice byte-identical',
            'bin': f'assets/bin/prg_bank_{n}.bin',
        })
    c_parts.append('const uint8_t JackalPrgBanks[JACKAL_PRG_BANK_COUNT][JACKAL_PRG_BANK_SIZE] = {')
    c_parts += rows
    c_parts.append('};')
    c_parts.append('')
    (gen / 'jackal_prg_banks.c').write_text('\n'.join(c_parts) + '\n', encoding='ascii', newline='\n')
    (gen / 'jackal_prg_banks.h').write_text('\n'.join(h_parts) + '\n', encoding='ascii', newline='\n')

def emit_all(rom, registry, out_dir):
    out = Path(out_dir)
    gen = out / 'JackalPkg' / 'Generated'
    bindir = out / 'assets' / 'bin'
    gen.mkdir(parents=True, exist_ok=True)
    bindir.mkdir(parents=True, exist_ok=True)
    c_parts = ['/* Auto-generated by tools/rom_extract. DO NOT EDIT. */',
               '#include "jackal_assets.h"', '']
    h_parts = ['/* Auto-generated by tools/rom_extract. DO NOT EDIT. */',
               '#ifndef JACKAL_ASSETS_H', '#define JACKAL_ASSETS_H', '',
               '#include <stdint.h>', '']
    manifest = {'tool': 'rom_extract', 'entries': []}
    for e in registry:
        raw = entry_bytes(rom, e)
        ident = 'jackal_' + c_ident(e.name)
        (bindir / f'{e.name}.bin').write_bytes(raw)
        c_parts.append(f'/* {e.name} bank{e.bank} cpu ${e.cpu:04X} asm {e.asm_ref} ({e.evidence}) */')
        c_parts.append(f'const uint8_t {ident}[{len(raw)}] = {{')
        c_parts += _hex_lines(raw)
        c_parts.append('};')
        c_parts.append('')
        h_parts.append(f'extern const uint8_t {ident}[{len(raw)}];')
        manifest['entries'].append({
            'name': e.name, 'bank': e.bank, 'cpu': f'0x{e.cpu:04X}',
            'kind': e.kind, 'count': e.count, 'length': len(raw),
            'crc32': f'0x{zlib.crc32(raw) & 0xFFFFFFFF:08X}',
            'asm_ref': e.asm_ref, 'evidence': e.evidence,
            'bin': f'assets/bin/{e.name}.bin',
        })
    h_parts += ['', '#endif']
    _emit_prg_banks(rom, gen, bindir, manifest)
    c_path = gen / 'jackal_assets.c'
    h_path = gen / 'jackal_assets.h'
    c_path.write_text('\n'.join(c_parts) + '\n', encoding='ascii', newline='\n')
    h_path.write_text('\n'.join(h_parts) + '\n', encoding='ascii', newline='\n')
    man_path = out / 'assets' / 'manifest.json'
    man_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=True) + '\n',
                        encoding='ascii', newline='\n')
    return {'c': str(c_path), 'h': str(h_path), 'manifest': str(man_path)}
